stages:
  train_model:
    cmd: python src/train_model.py
    deps:
    - data/processed/X_test.csv
    - data/processed/X_train.csv
    - data/processed/y_test.csv
    - data/processed/y_train.csv
    - src/train_model.py
    params:
    - model.random_forest.max_depth
    - model.random_forest.n_estimators
    - threshold.probability_cutoff
    outs:
    - models/best_model.pkl
    metrics:
    - metrics.json:
        cache: false
