data:
  raw_data_path: data/raw/creditcard.csv
  processed_data_path: data/processed/

split:
  test_size: 0.2
  random_state: 42

models:
  train_models: ["xgboost", "random_forest"]  # List of models to train and compare

  xgboost:
    max_depth: 6
    learning_rate: 0.1
    n_estimators: 100
    subsample: 0.8
    colsample_bytree: 0.8
    objective: binary:logistic
    random_state: 42

  random_forest:
    n_estimators: 100
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    random_state: 42

mlflow:
  experiment_name: fraud_detection_experiments
  tracking_uri: http://127.0.0.1:5000
  registered_model_name: best_fraud_model
